name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.2.0'

      - name: Terraform fmt
        run: terraform fmt
        continue-on-error: false

      - name: Terraform validate
        run: terraform validate
        continue-on-error: false

      - name: Terraform plan
        run: terraform plan
        continue-on-error: false

      - name: Terraform apply
        run: |
          terraform apply -auto-approve
        env:
          TF_AUTO_APPROVE: true
        continue-on-error: false